# Fast Reverse Proxy Client Configuration
# This file configures the client side of the FRP tunnel
# It connects to the Alibaba Cloud server and forwards traffic

[common]
# Alibaba Cloud server IP
server_addr = "47.106.67.151"
# FRP server port
server_port = 7001
# Authentication token (must match server)
token = "2ChenjinyU080511"
# Enable detailed logging
log_level = "debug"
# Add connection settings
login_fail_exit = false
heartbeat_interval = 20
heartbeat_timeout = 90
# Add retry settings
max_pool_count = 5
max_retry_count = 3

[web]
# Protocol type
type = "tcp"
# Local address to forward from
local_ip = "127.0.0.1"
# Local port (Next.js)
local_port = 3000
# Remote port on server
remote_port = 8081
# Prevent redirection
use_encryption = true
use_compression = true
# Add path handling settings
route_by_http_user = false
custom_domains = ["jinyu.asia"]